# +----------------------------------------------------------------------------+
# | License Agreement                                                          |
# |                                                                            |
# | Copyright (c) 1991-2009 Altera Corporation, San Jose, California, USA.     |
# | All rights reserved.                                                       |
# |                                                                            |
# | Any megafunction design, and related net list (encrypted or decrypted),    |
# |  support information, device programming or simulation file, and any other |
# |  associated documentation or information provided by Altera or a partner   |
# |  under Altera's Megafunction Partnership Program may be used only to       |
# |  program PLD devices (but not masked PLD devices) from Altera.  Any other  |
# |  use of such megafunction design, net list, support information, device    |
# |  programming or simulation file, or any other related documentation or     |
# |  information is prohibited for any other purpose, including, but not       |
# |  limited to modification, reverse engineering, de-compiling, or use with   |
# |  any other silicon devices, unless such use is explicitly licensed under   |
# |  a separate agreement with Altera or a megafunction partner.  Title to     |
# |  the intellectual property, including patents, copyrights, trademarks,     |
# |  trade secrets, or maskworks, embodied in any such megafunction design,    |
# |  net list, support information, device programming or simulation file, or  |
# |  any other related documentation or information provided by Altera or a    |
# |  megafunction partner, remains with Altera, the megafunction partner, or   |
# |  their respective licensors.  No other licenses, including any licenses    |
# |  needed under any third party's intellectual property, are provided herein.|
# |  Copying or modifying any file, or portion thereof, to which this notice   |
# |  is attached violates this copyright.                                      |
# |                                                                            |
# | THIS FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    |
# | IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   |
# | FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    |
# | THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER |
# | LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    |
# | FROM, OUT OF OR IN CONNECTION WITH THIS FILE OR THE USE OR OTHER DEALINGS  |
# | IN THIS FILE.                                                              |
# |                                                                            |
# | This agreement shall be governed in all respects by the laws of the State  |
# |  of California and by the laws of the United States of America.            |
# |                                                                            |
# +----------------------------------------------------------------------------+

# TCL File Generated by Altera University Program
# DO NOT MODIFY

# +-----------------------------------
# | module altera_up_avalon_audio_and_video_config
# | 
set_module_property DESCRIPTION "I2C bus for audio and video configuration on DE boards"
set_module_property NAME altera_up_avalon_audio_and_video_config
set_module_property VERSION 9.0
set_module_property GROUP "University Program/Audio & Video"
set_module_property AUTHOR "Altera University Program"
set_module_property DISPLAY_NAME "Audio and Video Config"
set_module_property DATASHEET_URL "ftp.altera.com/up/archive/QII_9.0/Altera_Material/University_Program_IP/Audio_Video/Audio_and_Video_Config.pdf"
#set_module_property TOP_LEVEL_HDL_FILE Altera_UP_Avalon_Audio_and_Video_Config.v
#set_module_property TOP_LEVEL_HDL_MODULE Altera_UP_Avalon_Audio_and_Video_Config
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
set_module_property VALIDATION_CALLBACK validate
set_module_property ELABORATION_CALLBACK elaborate
set_module_property GENERATION_CALLBACK generate
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
#add_file Altera_UP_Avalon_Audio_and_Video_Config.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter device string "On Board - Audio and Video (DE2)" 
set_parameter_property device DISPLAY_NAME "Audio/Video Device"
set_parameter_property device GROUP "Components"
set_parameter_property device UNITS None
set_parameter_property device AFFECTS_PORT_WIDTHS true
set_parameter_property device ALLOWED_RANGES {"On Board - Audio only (DE1)" "On Board - Audio and Video (DE2)" "1.3 Megapixel Camera (TRDB_DC2)" "LCD Screen (TRDB_LCM)"}
set_parameter_property device VISIBLE true
set_parameter_property device ENABLED true

add_parameter eai boolean false
set_parameter_property eai DISPLAY_NAME "Auto Initialize Device(s)"
set_parameter_property eai GROUP "Components"
set_parameter_property eai UNITS None
set_parameter_property eai AFFECTS_PORT_WIDTHS true
set_parameter_property eai VISIBLE true
set_parameter_property eai ENABLED true

add_parameter audio_in string "Microphone to ADC"
set_parameter_property audio_in DISPLAY_NAME "Audio In Path"
set_parameter_property audio_in GROUP "Auto Initialize Parameters for Audio"
set_parameter_property audio_in UNITS None
set_parameter_property audio_in AFFECTS_PORT_WIDTHS true
set_parameter_property audio_in ALLOWED_RANGES {"Microphone to ADC" "Line In to ADC"}
set_parameter_property audio_in VISIBLE true
set_parameter_property audio_in ENABLED false

add_parameter dac_enable boolean true
set_parameter_property dac_enable DISPLAY_NAME "Audio Out - Enable DAC Output"
set_parameter_property dac_enable GROUP "Auto Initialize Parameters for Audio"
set_parameter_property dac_enable UNITS None
set_parameter_property dac_enable AFFECTS_PORT_WIDTHS true
set_parameter_property dac_enable VISIBLE true
set_parameter_property dac_enable ENABLED false

add_parameter mic_bypass boolean false
set_parameter_property mic_bypass DISPLAY_NAME "Audio Out - Microphone Bypass"
set_parameter_property mic_bypass GROUP "Auto Initialize Parameters for Audio"
set_parameter_property mic_bypass UNITS None
set_parameter_property mic_bypass AFFECTS_PORT_WIDTHS true
set_parameter_property mic_bypass VISIBLE true
set_parameter_property mic_bypass ENABLED false

add_parameter line_in_bypass boolean false
set_parameter_property line_in_bypass DISPLAY_NAME "Audio Out - Line In Bypass"
set_parameter_property line_in_bypass GROUP "Auto Initialize Parameters for Audio"
set_parameter_property line_in_bypass UNITS None
set_parameter_property line_in_bypass AFFECTS_PORT_WIDTHS true
set_parameter_property line_in_bypass VISIBLE true
set_parameter_property line_in_bypass ENABLED false

add_parameter mic_attenuation string "-6dB"
set_parameter_property mic_attenuation DISPLAY_NAME "Microphone Attenuation"
set_parameter_property mic_attenuation GROUP "Auto Initialize Parameters for Audio"
set_parameter_property mic_attenuation UNITS None
set_parameter_property mic_attenuation AFFECTS_PORT_WIDTHS true
set_parameter_property mic_attenuation ALLOWED_RANGES {"-6dB" "-9dB" "-12dB" "-15dB"}
set_parameter_property mic_attenuation VISIBLE false
set_parameter_property mic_attenuation ENABLED false

add_parameter data_format string "Left Justified"
set_parameter_property data_format DISPLAY_NAME "Data Format"
set_parameter_property data_format GROUP "Auto Initialize Parameters for Audio"
set_parameter_property data_format UNITS None
set_parameter_property data_format AFFECTS_PORT_WIDTHS true
set_parameter_property data_format ALLOWED_RANGES {"DSP Mode" "I2S Format" "Left Justified" "Right Justified"}
set_parameter_property data_format VISIBLE true
set_parameter_property data_format ENABLED false

add_parameter bit_length int 24
set_parameter_property bit_length DISPLAY_NAME "Bit Length"
set_parameter_property bit_length GROUP "Auto Initialize Parameters for Audio"
set_parameter_property bit_length UNITS None
set_parameter_property bit_length AFFECTS_PORT_WIDTHS true
set_parameter_property bit_length ALLOWED_RANGES {32 24 20 16}
set_parameter_property bit_length VISIBLE true
set_parameter_property bit_length ENABLED false

add_parameter bosr string "250fs/256fs"
set_parameter_property bosr DISPLAY_NAME "Base Over-Sampling Rate"
set_parameter_property bosr GROUP "Auto Initialize Parameters for Audio"
set_parameter_property bosr UNITS None
set_parameter_property bosr AFFECTS_PORT_WIDTHS true
set_parameter_property bosr ALLOWED_RANGES {"250fs/256fs" "272fs/384fs"}
set_parameter_property bosr VISIBLE true
set_parameter_property bosr ENABLED false

add_parameter sample_rate int 0
set_parameter_property sample_rate DISPLAY_NAME "Sampling Rate"
set_parameter_property sample_rate GROUP "Auto Initialize Parameters for Audio"
set_parameter_property sample_rate UNITS None
set_parameter_property sample_rate AFFECTS_PORT_WIDTHS true
set_parameter_property sample_rate ALLOWED_RANGES 0:15
set_parameter_property sample_rate VISIBLE true
set_parameter_property sample_rate ENABLED false
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point external_interface
# | 
add_interface external_interface conduit end

set_interface_property external_interface ASSOCIATED_CLOCK clock_reset

add_interface_port external_interface I2C_SDAT export Bidir 1
add_interface_port external_interface I2C_SCLK export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | Validation function
# | 
proc validate {} {
	set device [ get_parameter_value "device" ]
	set eai [ get_parameter_value "eai" ]
	set audio_in [ get_parameter_value "audio_in" ]
	set dac_enable [ get_parameter_value "dac_enable" ]
	set mic_bypass [ get_parameter_value "mic_bypass" ]
	set line_in_bypass [ get_parameter_value "line_in_bypass" ]
	set mic_attenuation [ get_parameter_value "mic_attenuation" ]
	set data_format [ get_parameter_value "data_format" ]
	set bit_length [ get_parameter_value "bit_length" ]
	set bosr [ get_parameter_value "bosr" ]
	set sample_rate [ get_parameter_value "sample_rate" ]
	
	set_parameter_property audio_in ENABLED false
	set_parameter_property dac_enable ENABLED false
	set_parameter_property mic_bypass ENABLED false
	set_parameter_property line_in_bypass ENABLED false
	set_parameter_property mic_attenuation ENABLED false
	set_parameter_property data_format ENABLED false
	set_parameter_property bit_length ENABLED false
	set_parameter_property bosr ENABLED false
	set_parameter_property sample_rate ENABLED false

	if { $device == "1.3 Megapixel Camera (TRDB_DC2)" } {
	} elseif { $device == "LCD Screen (TRDB_LCM)" } {
	} else {
		if { $eai } {
			set_parameter_property audio_in ENABLED true
			set_parameter_property dac_enable ENABLED true
			set_parameter_property mic_bypass ENABLED true
			set_parameter_property line_in_bypass ENABLED true
			set_parameter_property mic_attenuation ENABLED true
			set_parameter_property data_format ENABLED true
			set_parameter_property bit_length ENABLED true
			set_parameter_property bosr ENABLED true
			set_parameter_property sample_rate ENABLED true

			if { $data_format == "Left Justified" } {
			} else {
				send_message info "The data format must be Left Justified, if using the Altera UP Audio IP Cores."
			}
		}
	}
}
# | 
# +-----------------------------------

# +-----------------------------------
# | Elaboration function
# | 
proc elaborate {} {
	set device [ get_parameter_value "device" ]
	set eai [ get_parameter_value "eai" ]
	set audio_in [ get_parameter_value "audio_in" ]
	set dac_enable [ get_parameter_value "dac_enable" ]
	set mic_bypass [ get_parameter_value "mic_bypass" ]
	set line_in_bypass [ get_parameter_value "line_in_bypass" ]
	set mic_attenuation [ get_parameter_value "mic_attenuation" ]
	set data_format [ get_parameter_value "data_format" ]
	set bit_length [ get_parameter_value "bit_length" ]
	set bosr [ get_parameter_value "bosr" ]
	set sample_rate [ get_parameter_value "sample_rate" ]

	if { $device == "1.3 Megapixel Camera (TRDB_DC2)" } {
		# +-----------------------------------
		# | connection point avalon_trdb_dc2_config_slave
		# | 
		add_interface avalon_trdb_dc2_config_slave avalon end
		set_interface_property avalon_trdb_dc2_config_slave holdTime 0
		set_interface_property avalon_trdb_dc2_config_slave linewrapBursts false
		set_interface_property avalon_trdb_dc2_config_slave minimumUninterruptedRunLength 1
		set_interface_property avalon_trdb_dc2_config_slave bridgesToMaster ""
		set_interface_property avalon_trdb_dc2_config_slave isMemoryDevice false
		set_interface_property avalon_trdb_dc2_config_slave burstOnBurstBoundariesOnly false
		set_interface_property avalon_trdb_dc2_config_slave addressSpan 16
		set_interface_property avalon_trdb_dc2_config_slave timingUnits Cycles
		set_interface_property avalon_trdb_dc2_config_slave setupTime 0
		set_interface_property avalon_trdb_dc2_config_slave writeWaitTime 0
		set_interface_property avalon_trdb_dc2_config_slave isNonVolatileStorage false
		set_interface_property avalon_trdb_dc2_config_slave addressAlignment DYNAMIC
		set_interface_property avalon_trdb_dc2_config_slave maximumPendingReadTransactions 0
		set_interface_property avalon_trdb_dc2_config_slave readWaitTime 1
		set_interface_property avalon_trdb_dc2_config_slave readLatency 1
		set_interface_property avalon_trdb_dc2_config_slave printableDevice false
		
		set_interface_property avalon_trdb_dc2_config_slave ASSOCIATED_CLOCK clock_reset
		
		add_interface_port avalon_trdb_dc2_config_slave dc_address address Input 2
		add_interface_port avalon_trdb_dc2_config_slave dc_byteenable byteenable Input 4
		add_interface_port avalon_trdb_dc2_config_slave dc_chipselect chipselect Input 1
		add_interface_port avalon_trdb_dc2_config_slave dc_read read Input 1
		add_interface_port avalon_trdb_dc2_config_slave dc_write write Input 1
		add_interface_port avalon_trdb_dc2_config_slave dc_writedata writedata Input 32
		add_interface_port avalon_trdb_dc2_config_slave dc_readdata readdata Output 32
		add_interface_port avalon_trdb_dc2_config_slave dc_waitrequest waitrequest Output 1
		# | 
		# +-----------------------------------
	} elseif { $device == "LCD Screen (TRDB_LCM)" } {
		# +-----------------------------------
		# | connection point avalon_trdb_lcm_config_slave
		# | 
		add_interface avalon_trdb_lcm_config_slave avalon end
		set_interface_property avalon_trdb_lcm_config_slave holdTime 0
		set_interface_property avalon_trdb_lcm_config_slave linewrapBursts false
		set_interface_property avalon_trdb_lcm_config_slave minimumUninterruptedRunLength 1
		set_interface_property avalon_trdb_lcm_config_slave bridgesToMaster ""
		set_interface_property avalon_trdb_lcm_config_slave isMemoryDevice false
		set_interface_property avalon_trdb_lcm_config_slave burstOnBurstBoundariesOnly false
		set_interface_property avalon_trdb_lcm_config_slave addressSpan 16
		set_interface_property avalon_trdb_lcm_config_slave timingUnits Cycles
		set_interface_property avalon_trdb_lcm_config_slave setupTime 0
		set_interface_property avalon_trdb_lcm_config_slave writeWaitTime 0
		set_interface_property avalon_trdb_lcm_config_slave isNonVolatileStorage false
		set_interface_property avalon_trdb_lcm_config_slave addressAlignment DYNAMIC
		set_interface_property avalon_trdb_lcm_config_slave maximumPendingReadTransactions 0
		set_interface_property avalon_trdb_lcm_config_slave readWaitTime 1
		set_interface_property avalon_trdb_lcm_config_slave readLatency 1
		set_interface_property avalon_trdb_lcm_config_slave printableDevice false
		
		set_interface_property avalon_trdb_lcm_config_slave ASSOCIATED_CLOCK clock_reset
		
		add_interface_port avalon_trdb_lcm_config_slave lcm_address address Input 2
		add_interface_port avalon_trdb_lcm_config_slave lcm_byteenable byteenable Input 4
		add_interface_port avalon_trdb_lcm_config_slave lcm_chipselect chipselect Input 1
		add_interface_port avalon_trdb_lcm_config_slave lcm_read read Input 1
		add_interface_port avalon_trdb_lcm_config_slave lcm_write write Input 1
		add_interface_port avalon_trdb_lcm_config_slave lcm_writedata writedata Input 32
		add_interface_port avalon_trdb_lcm_config_slave lcm_readdata readdata Output 32
		add_interface_port avalon_trdb_lcm_config_slave lcm_waitrequest waitrequest Output 1
		# | 
		# +-----------------------------------

		# +-----------------------------------
		# | connection point external_interface
		# | 
		add_interface_port external_interface I2C_SCEN export Output 1
		# | 
		# +-----------------------------------
	} else {
		# +-----------------------------------
		# | connection point avalon_on_board_config_slave
		# | 
		add_interface avalon_on_board_config_slave avalon end
		set_interface_property avalon_on_board_config_slave holdTime 0
		set_interface_property avalon_on_board_config_slave linewrapBursts false
		set_interface_property avalon_on_board_config_slave minimumUninterruptedRunLength 1
		set_interface_property avalon_on_board_config_slave bridgesToMaster ""
		set_interface_property avalon_on_board_config_slave isMemoryDevice false
		set_interface_property avalon_on_board_config_slave burstOnBurstBoundariesOnly false
		set_interface_property avalon_on_board_config_slave addressSpan 32
		set_interface_property avalon_on_board_config_slave timingUnits Cycles
		set_interface_property avalon_on_board_config_slave setupTime 0
		set_interface_property avalon_on_board_config_slave writeWaitTime 0
		set_interface_property avalon_on_board_config_slave isNonVolatileStorage false
		set_interface_property avalon_on_board_config_slave addressAlignment DYNAMIC
		set_interface_property avalon_on_board_config_slave maximumPendingReadTransactions 0
		set_interface_property avalon_on_board_config_slave readWaitTime 1
		set_interface_property avalon_on_board_config_slave readLatency 1
		set_interface_property avalon_on_board_config_slave printableDevice false
		
		set_interface_property avalon_on_board_config_slave ASSOCIATED_CLOCK clock_reset
		
		add_interface_port avalon_on_board_config_slave ob_address address Input 3
		add_interface_port avalon_on_board_config_slave ob_byteenable byteenable Input 4
		add_interface_port avalon_on_board_config_slave ob_chipselect chipselect Input 1
		add_interface_port avalon_on_board_config_slave ob_read read Input 1
		add_interface_port avalon_on_board_config_slave ob_write write Input 1
		add_interface_port avalon_on_board_config_slave ob_writedata writedata Input 32
		add_interface_port avalon_on_board_config_slave ob_readdata readdata Output 32
		add_interface_port avalon_on_board_config_slave ob_waitrequest waitrequest Output 1
		# | 
		# +-----------------------------------
	}
}
# | 
# +-----------------------------------

# +-----------------------------------
# | Generation function
# | 
proc generate {} {
	send_message info "Starting Generation of Audio and Video Config"

	# get generation settings
	set language [ format "lang=%s" [ get_generation_setting HDL_LANGUAGE ] ]
	set outdir [ format "dir=%s" [ get_generation_setting OUTPUT_DIRECTORY ] ]
	set outname [ format "name=%s" [ get_generation_setting OUTPUT_NAME ] ]

	# get parameter values
	set device [ get_parameter_value "device" ]
	set eai [ get_parameter_value "eai" ]
	set audio_in [ get_parameter_value "audio_in" ]
	set dac_enable [ get_parameter_value "dac_enable" ]
	set mic_bypass [ get_parameter_value "mic_bypass" ]
	set line_in_bypass [ get_parameter_value "line_in_bypass" ]
	set mic_attenuation [ get_parameter_value "mic_attenuation" ]
	set data_format [ get_parameter_value "data_format" ]
	set bit_length [ get_parameter_value "bit_length" ]
	set bosr [ get_parameter_value "bosr" ]
	set sample_rate [ get_parameter_value "sample_rate" ]

	set i2c_bus_mode [ format "I2C_BUS_MODE:1'b%d" [ string match "LCD Screen*" $device ] ]
	if { $device == "On Board - Audio only (DE1)" } {
		set cfg_type "CFG_TYPE:8'h00"
	} elseif { $device == "On Board - Audio and Video (DE2)" } {
		set cfg_type "CFG_TYPE:8'h01"
	} elseif { $device == "1.3 Megapixel Camera (TRDB_DC2)" } {
		set cfg_type "CFG_TYPE:8'h02"
	} else {
		set cfg_type "CFG_TYPE:8'h03"
	}

	set line_in_bypass 	[ expr [ string match "true" $line_in_bypass ] * 8 ]
	set dac_enable 		[ expr [ string match "true" $dac_enable ] * 16 ]
	set mic_bypass 		[ expr [ string match "true" $mic_bypass ] * 64 ]
	if { $audio_in == "Microphone to ADC" } {
		set aud_adc_path [ format "AUD_ADC_PATH:9'd%d" [ expr [ expr $mic_bypass + $dac_enable ] + [ expr $line_in_bypass + 133 ] ] ]
	} elseif { $mic_bypass } {
		set aud_adc_path [ format "AUD_ADC_PATH:9'd%d" [ expr [ expr $mic_bypass + $dac_enable ] + [ expr $line_in_bypass + 129 ] ] ]
	} else {
		set aud_adc_path [ format "AUD_ADC_PATH:9'd%d" [ expr [ expr $mic_bypass + $dac_enable ] + [ expr $line_in_bypass + 130 ] ] ]
	}

	if { $data_format == "DSP Mode" } {
		set data_format 3 
	} elseif { $data_format == "I2S Format" } {
		set data_format 2 
	} elseif { $data_format == "Left Justified" } {
		set data_format 1 
	} else {
		set data_format 0 
	}
	if { $bit_length == 32 } {
		set bit_length 3
	} elseif { $bit_length == 24 } {
		set bit_length 2
	} elseif { $bit_length == 20 } {
		set bit_length 1
	} else {
		set bit_length 0
	}
	set aud_data_format [ format "AUD_DATA_FORMAT:9'd%d" [ expr [ expr $bit_length * 4 ] + [ expr $data_format + 64 ] ] ]

	if { $bosr == "250fs/256fs" } {
		set bosr 0
	} else {
		set bosr 2
	}
	set sample_rate [ expr $sample_rate * 4 ]
	set aud_sample_ctrl [ format "AUD_SAMPLE_CTRL:9'd%d" [ expr $bosr + $sample_rate ] ]

	# set section value
	set use_ob_mode	 [ format "USE_OB_MODE:%d" [ string match "On Board*" $device ] ]
	set use_dc_mode	 [ format "USE_DC_MODE:%d" [ string match "1.3*" $device ] ]
	set use_lcm_mode [ format "USE_LCM_MODE:%d" [ string match "LCD Screen*" $device ] ]

	set use_ob_a_mode	 [ format "USE_OB_A_MODE:%d" [ string match "On Board - Audio only (DE1)" $device ] ]
	set use_ob_av_mode	 [ format "USE_OB_AV_MODE:%d" [ string match "On Board - Audio and Video (DE2)" $device ] ]
	set mode_sections "$use_ob_mode;$use_dc_mode;$use_lcm_mode;$use_ob_a_mode;$use_ob_av_mode" 

	if { $eai } {
		set use_ai		"USE_AUTO_INIT:1"
		set use_ob_ai	[ format "USE_OB_AUTO_INIT:%d" [ string match "On Board*" $device ] ]
		set use_dc_ai	[ format "USE_DC_AUTO_INIT:%d" [ string match "1.3*" $device ] ]
		set use_lcm_ai	[ format "USE_LCM_AUTO_INIT:%d" [ string match "LCD Screen*" $device ] ]
		set ai_sections "$use_ai;$use_ob_ai;$use_dc_ai;$use_lcm_ai"
	} else {
		set ai_sections "USE_AUTO_INIT:0;USE_OB_AUTO_INIT:0;USE_DC_AUTO_INIT:0;USE_LCM_AUTO_INIT:0"
	}
	
	# set top_level_ports and external_port
	set top_level_name [ format "top_level_name=%s" [ get_project_property QUARTUS_PROJECT_NAME ] ]
	set top_level_ports "top_level_ports=I2C_SDAT:Bidir:1;I2C_SCLK:Output:1"
	set module_ports "module_ports=I2C_SDAT:Bidir:1:I2C_SDAT;I2C_SCLK:Output:1:I2C_SCLK"

	# set arguments
	if { $eai } {
		if { $device == "1.3 Megapixel Camera (TRDB_DC2)" } {
			set files "files=Altera_UP_Avalon_Audio_and_Video_Config.v;Altera_UP_I2C.v;Altera_UP_I2C_DC_Auto_Initialize.v;Altera_UP_Slow_Clock_Generator.v"
		} elseif { $device == "LCD Screen (TRDB_LCM)" } {
			set files "files=Altera_UP_Avalon_Audio_and_Video_Config.v;Altera_UP_I2C.v;Altera_UP_I2C_LCM_Auto_Initialize.v;Altera_UP_Slow_Clock_Generator.v"
		} else {
			set files "files=Altera_UP_Avalon_Audio_and_Video_Config.v;Altera_UP_I2C.v;Altera_UP_I2C_AV_Auto_Initialize.v;Altera_UP_Slow_Clock_Generator.v"
		}
	} else {
		set files "files=Altera_UP_Avalon_Audio_and_Video_Config.v;Altera_UP_I2C.v;Altera_UP_Slow_Clock_Generator.v"
	}
	set params "$i2c_bus_mode;$cfg_type;$aud_adc_path;$aud_data_format;$aud_sample_ctrl"
	set sections "$mode_sections;$ai_sections" 

	# get generation settings
#	set dest_language	[ get_generation_setting HDL_LANGUAGE ]
	set dest_dir 		[ get_generation_setting OUTPUT_DIRECTORY ]
	set dest_name		[ get_generation_setting OUTPUT_NAME ]
	add_file "$dest_dir$dest_name.v" {SYNTHESIS SIMULATION}

	# Generate HDL
	source "UP_IP_Generator.tcl"
	up_generate "$dest_dir$dest_name.v" "hdl/Altera_UP_Avalon_Audio_and_Video_Config.v" $dest_name $params $sections
	file copy -force "hdl/Altera_UP_I2C.v" $dest_dir
	file copy -force "hdl/Altera_UP_I2C_DC_Auto_Initialize.v" $dest_dir
	file copy -force "hdl/Altera_UP_I2C_LCM_Auto_Initialize.v" $dest_dir
	file copy -force "hdl/Altera_UP_I2C_AV_Auto_Initialize.v" $dest_dir
	file copy -force "hdl/Altera_UP_Slow_Clock_Generator.v" $dest_dir
}
# | 
# +-----------------------------------

