# TCL File Generated by Component Editor 9.1sp2
# Thu May 27 02:15:10 CEST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | analyzer_input "analyzer_input" v1.0
# | null 2010.05.27.02:15:10
# | 
# | 
# | C:/Data/Proyektz/Tidied/IFE/Sem6/DGH1/analyzer_input.vhd
# | 
# |    ./analyzer_input.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module analyzer_input
# | 
set_module_property NAME analyzer_input
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property DISPLAY_NAME analyzer_input
set_module_property TOP_LEVEL_HDL_FILE analyzer_input.vhd
set_module_property TOP_LEVEL_HDL_MODULE analyzer_input
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file analyzer_input.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
add_interface_port clock reset reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ASSOCIATED_CLOCK clock
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave readdata readdata Output 128
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point audio_in
# | 
add_interface audio_in conduit end

set_interface_property audio_in ASSOCIATED_CLOCK clock
set_interface_property audio_in ENABLED true

add_interface_port audio_in x_in export Input 64
add_interface_port audio_in y_in export Input 64
# | 
# +-----------------------------------
