# TCL File Generated by Component Editor 9.1sp1
# Tue May 11 17:47:45 CEST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | membuffer "membuffer" v1.0
# | null 2010.05.11.17:47:45
# | 
# | 
# | E:/vhdl/VGA-Handling/audio/membuffer.vhd
# | 
# |    ./membuffer.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module membuffer
# | 
set_module_property NAME membuffer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property DISPLAY_NAME membuffer
set_module_property TOP_LEVEL_HDL_FILE membuffer.vhd
set_module_property TOP_LEVEL_HDL_MODULE membuffer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file membuffer.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter BASE_ADDR INTEGER 0
set_parameter_property BASE_ADDR DEFAULT_VALUE 0
set_parameter_property BASE_ADDR DISPLAY_NAME BASE_ADDR
set_parameter_property BASE_ADDR UNITS None
set_parameter_property BASE_ADDR DISPLAY_HINT ""
set_parameter_property BASE_ADDR AFFECTS_GENERATION false
set_parameter_property BASE_ADDR HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point audio_port
# | 
add_interface audio_port conduit end

set_interface_property audio_port ASSOCIATED_CLOCK clock_reset
set_interface_property audio_port ENABLED true

add_interface_port audio_port sample_clk export Input 1
add_interface_port audio_port delay_time export Input 16
add_interface_port audio_port sample_left_in export Input 16
add_interface_port audio_port sample_right_in export Input 16
add_interface_port audio_port sample_left_out export Output 16
add_interface_port audio_port sample_right_out export Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_master
# | 
add_interface avalon_master avalon start
set_interface_property avalon_master associatedClock clock_reset
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master linewrapBursts false

set_interface_property avalon_master ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_master ENABLED true

add_interface_port avalon_master address address Output 32
add_interface_port avalon_master read read Output 1
add_interface_port avalon_master readdata readdata Input 32
add_interface_port avalon_master waitrequest waitrequest Input 1
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master writedata writedata Output 32
# | 
# +-----------------------------------
