# TCL File Generated by Component Editor 8.0
# Fri Feb 27 16:12:14 EST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | Altera_UP_Flash_Memory_IP_Core_Avalon_Interface "Altera_UP_Flash_Memory_IP_Core_Avalon_Interface" v1.0
# | null 2009.02.27.16:12:14
# | Flash Memory Interface Module
# | 
# +-----------------------------------


# +-----------------------------------
# | module Altera_UP_Flash_Memory_IP_Core_Avalon_Interface
# | 
set_module_property DESCRIPTION "Flash Memory Interface Module"
set_module_property NAME Altera_UP_Flash_Memory_IP_Core_Avalon_Interface
set_module_property VERSION 1.0
set_module_property GROUP "University Program/Memory"
set_module_property DISPLAY_NAME "Altera UP Flash Memory IP Core"
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.std_logic_arith.all ieee.std_logic_unsigned.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE hdl/Altera_UP_Flash_Memory_IP_Core_Avalon_Interface.vhd
set_module_property TOP_LEVEL_HDL_MODULE Altera_UP_Flash_Memory_IP_Core_Avalon_Interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/Altera_UP_Flash_Memory_IP_Core_Avalon_Interface.vhd {SYNTHESIS SIMULATION}
add_file hdl/Altera_UP_Flash_Memory_Controller.vhd {SYNTHESIS SIMULATION}
add_file hdl/Altera_UP_Flash_Memory_IP_Core_Standalone.vhd {SYNTHESIS SIMULATION}
add_file hdl/Altera_UP_Flash_Memory_User_Interface.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter FLASH_MEMORY_ADDRESS_WIDTH int 22
set_parameter_property FLASH_MEMORY_ADDRESS_WIDTH DISPLAY_NAME FLASH_MEMORY_ADDRESS_WIDTH
set_parameter_property FLASH_MEMORY_ADDRESS_WIDTH UNITS None
set_parameter_property FLASH_MEMORY_ADDRESS_WIDTH AFFECTS_PORT_WIDTHS true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point flash_data
# | 
add_interface flash_data avalon end
set_interface_property flash_data holdTime 0
set_interface_property flash_data linewrapBursts false
set_interface_property flash_data minimumUninterruptedRunLength 1
set_interface_property flash_data bridgesToMaster ""
set_interface_property flash_data isMemoryDevice false
set_interface_property flash_data burstOnBurstBoundariesOnly false
set_interface_property flash_data addressSpan 4
set_interface_property flash_data timingUnits Cycles
set_interface_property flash_data setupTime 0
set_interface_property flash_data writeWaitTime 0
set_interface_property flash_data isNonVolatileStorage false
set_interface_property flash_data addressAlignment DYNAMIC
set_interface_property flash_data maximumPendingReadTransactions 0
set_interface_property flash_data readWaitTime 1
set_interface_property flash_data readLatency 0
set_interface_property flash_data printableDevice false

set_interface_property flash_data ASSOCIATED_CLOCK clock_sink

add_interface_port flash_data i_avalon_chip_select chipselect Input 1
add_interface_port flash_data i_avalon_write write Input 1
add_interface_port flash_data i_avalon_read read Input 1
add_interface_port flash_data i_avalon_address address Input -1
add_interface_port flash_data i_avalon_byteenable byteenable Input 4
add_interface_port flash_data i_avalon_writedata writedata Input 32
add_interface_port flash_data o_avalon_readdata readdata Output 32
add_interface_port flash_data o_avalon_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink ptfSchematicName ""

add_interface_port clock_sink i_clock clk Input 1
add_interface_port clock_sink i_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_sink

add_interface_port conduit_end FL_ADDR export Output -1
add_interface_port conduit_end FL_CE_N export Output 1
add_interface_port conduit_end FL_OE_N export Output 1
add_interface_port conduit_end FL_WE_N export Output 1
add_interface_port conduit_end FL_RST_N export Output 1
add_interface_port conduit_end FL_DQ export Bidir -1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point flash_erase_control
# | 
add_interface flash_erase_control avalon end
set_interface_property flash_erase_control holdTime 0
set_interface_property flash_erase_control linewrapBursts false
set_interface_property flash_erase_control minimumUninterruptedRunLength 1
set_interface_property flash_erase_control bridgesToMaster ""
set_interface_property flash_erase_control isMemoryDevice false
set_interface_property flash_erase_control burstOnBurstBoundariesOnly false
set_interface_property flash_erase_control addressSpan 4
set_interface_property flash_erase_control timingUnits Cycles
set_interface_property flash_erase_control setupTime 0
set_interface_property flash_erase_control writeWaitTime 0
set_interface_property flash_erase_control isNonVolatileStorage false
set_interface_property flash_erase_control addressAlignment DYNAMIC
set_interface_property flash_erase_control maximumPendingReadTransactions 0
set_interface_property flash_erase_control readWaitTime 1
set_interface_property flash_erase_control readLatency 0
set_interface_property flash_erase_control printableDevice false

set_interface_property flash_erase_control ASSOCIATED_CLOCK clock_sink

add_interface_port flash_erase_control i_avalon_erase_write write Input 1
add_interface_port flash_erase_control i_avalon_erase_read read Input 1
add_interface_port flash_erase_control i_avalon_erase_byteenable byteenable Input 4
add_interface_port flash_erase_control i_avalon_erase_writedata writedata Input 32
add_interface_port flash_erase_control i_avalon_erase_chip_select chipselect Input 1
add_interface_port flash_erase_control o_avalon_erase_readdata readdata Output 32
add_interface_port flash_erase_control o_avalon_erase_waitrequest waitrequest Output 1
# | 
# +-----------------------------------
